[package]
name = "P36"
version = "0.1.0"
authors = ["Tomoko Uchida <tomoko.uchida.1111@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
P35 = { path = "../P35" }